sudo: false

language: python

python:
    - "3.6"

install:
    - python3 -m pip install -r requirements.txt
    - python3 -m pip install -r requirements_devel.txt
    
script: 
    - paver
    - python3 -m pip install .
   
after_success:
    - coverage combine ./.coverage ./tests/behave/features/.coverage
    - codecov
    
